# Generated by Django 2.2.6 on 2022-07-10 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0002_auto_20220702_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
