# Generated by Django 2.2.6 on 2022-06-24 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=200, verbose_name='Receita')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('preparation_mode', models.TextField(verbose_name='Modo de Preparo')),
                ('preparation_time', models.IntegerField(verbose_name='Tempo de Preparo')),
                ('efficiency', models.CharField(max_length=100, verbose_name='Rendimento')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('date_recipe', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='data da publicação')),
            ],
        ),
    ]
