# Generated by Django 2.2.6 on 2022-06-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Recipe',
        ),
    ]
