# Generated by Django 2.2.6 on 2022-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0003_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture_recipe',
            field=models.ImageField(blank=True, upload_to='pictures/%d/%m/%Y', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
